development:
  adapter: redis
  url: redis://:12345678@pub-redis-12835.us-east-1-4.2.ec2.garantiadata.com:12835

test:
  adapter: async

production:
  adapter: redis
  url: redis://:12345678@pub-redis-12835.us-east-1-4.2.ec2.garantiadata.com:12835
